export default [
  'CLEAR_TABLE_FILTER_SETTINGS',
  'CLEAR_USER',
  'SET_MODAL_DATA',
  'SET_MODAL_STATE',
  'SET_TAB_VALUE',
  'SET_TABLE_FILTER_SETTINGS',
  'SET_TABLE_HIDDEN_COLUMNS',
  'SET_TABLE_PAGER_SETTINGS',
  'SET_TABLE_SORT_SETTINGS',
  'SORT_WORDS'
];
